blank_issues_enabled: false
contact_links:
  - name: Support Discord server
    url: https://discord.gg/NYBEhN7
    about: If you need help, have a question, or something isn't working, please ask in our Discord server!
  - name: Report WidgetBot Embed Bug
    url: https://github.com/widgetbot-io/embed/issues/new?assignees=&labels=bug&template=bug_report.md&title=
    about: The widgetbot-io/crate repo is only for issues with the crate button! If you need to report a bug with the embed itself, go to the embed repo.
  - name: Submit a WidgetBot Embed Feature Request
    url: https://github.com/widgetbot-io/embed/issues/new?assignees=&labels=suggestion&template=feature_request.md&title=
    about: The widgetbot-io/crate repo is only for issues with the crate button! If you need to submit a feature request for the embed itself, go to the embed repo.
  - name: Submit a WidgetBot Crate Issue
    url: https://github.com/widgetbot-io/crate/issues/new
    about: If you want to report a bug with or submit a feature request for the crate button specifically, create an issue here. For issues in the embed itself, use an option above.
  - name: See existing Crate button issues
    url: https://github.com/widgetbot-io/crate/issues
    about: Please look through the current issues before creating a new one, to make sure it hasn't been reported/suggested before!
